### ISSUE TITLE
Exception reading config file when restarting

### ISSUE THREAD

**Issue by rscadrde** [quaddy-services/escape-from-intranet#4]
```
2018-01-30T17:11:33.983:info:EscapeProxy:Start
2018-01-30T17:11:34.310:error:EscapeProxy:error
java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:80)
	at java.util.Properties$XmlSupport.load(Properties.java:1201)
	at java.util.Properties.loadFromXML(Properties.java:881)
	at de.quaddy_services.proxy.EscapeProxy.readConfig(EscapeProxy.java:128)
	at de.quaddy_services.proxy.EscapeProxy.main(EscapeProxy.java:45)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1014)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at sun.util.xml.PlatformXmlPropertiesProvider.getLoadingDoc(PlatformXmlPropertiesProvider.java:106)
	at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:78)
	... 4 more


```

**Comment by rscadrde** [comment]
Previous log:
```
2018-01-30T17:09:04.810:info:EscapeProxyWorkerSocket:finished
2018-01-30T17:09:04.816:info:EscapeProxyWorkerSocket:finished
2018-01-30T17:10:14.248:info:EscapeProxy:Save config C:\Users\dt0b35\escape-from-intranet.xml


```

**Comment by rscadrde** [comment]
fixed
